# Generated by Django 4.2.4 on 2023-09-07 23:49

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'BlogUser')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    
    add_blogpost = Permission.objects.get(codename='add_blogposts')
    change_blogpost = Permission.objects.get(codename='change_blogposts')
    delete_blogpost = Permission.objects.get(codename='delete_blogposts')
    view_blogpost = Permission.objects.get(codename='view_blogposts')
    
    creator_permissions = [
        add_blogpost,
        change_blogpost,
        delete_blogpost,
        view_blogpost
    ]
    
    creators = Group(name = 'creators')
    creators.save()
    creators.permissions.set(creator_permissions)
    
    subscribers = Group(name = 'subscriber')
    subscribers.save()
    subscribers.permissions.add(view_blogpost)
    
    for user in User.objects.all():
        if user.role == 'CREATOR':
            creators.user_set.add(user)
        if user.role == 'SUSCRIBER':
            subscribers.user_set.add(user)
    
    



class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_bloguser_profile_photo'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
