# Generated by Django 4.2.4 on 2023-08-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='blogposts',
            name='category',
            field=models.CharField(choices=[('Code', 'Code'), ('Stories', 'Stories')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogposts',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='posts.tags'),
        ),
    ]
