# Generated by Django 4.2.4 on 2023-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tags_blogposts_category_blogposts_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
