# Generated by Django 4.2.4 on 2023-09-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_blogposts_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
    ]
