# Generated by Django 4.2.4 on 2023-09-03 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_photo_blogposts_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='blogposts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='posts.blogposts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_for_blog_posts', to='posts.photo'),
        ),
    ]
