# Generated by Django 4.2.4 on 2023-09-07 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_remove_comment_name_comment_author_comment_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogposts',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='picture',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='picture_comment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
