# Generated by Django 4.2.4 on 2023-09-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_blogposts_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
