# Generated by Django 4.2.4 on 2023-09-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_blogposts_photo_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
